name: openfocusly
description: counters, focus, notes.
publish_to: 'none'
version: 2.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^11.5.1
flutter:
  assets:
    - assets/lang/
    - assets/audio/
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"